### ISSUE TITLE
How to debug the extension?

### ISSUE THREAD

**Issue by jjgod** [mitaki28/vscode-clang#19]
Hi,

I have VSCode 1.2 installed and trying to use this extension with an internal project. When I opened any C++ files (`.cpp`), there is no diagnostics information, nor does it autocompletes when I typed any triggering char (`.` for example).

Is there a good way to me to find out why the extension isn't working for me?

I did set up some `clang.cxxflags` in my workspace `settings.json`, it goes like this:

```
{
    "clang.cxxflags": [
        "-std=c++11",
        "-I${workspaceRoot}",
        "-fconstant-cfstrings",
    ]
}
```

But I don't get any help from that, removing it doesn't help either.

I cloned the repository and try to debug with [F5](https://code.visualstudio.com/docs/extensions/debugging-extensions), but it shows this error:

<img width="581" alt="screen shot 2016-06-07 at 7 12 10 pm" src="https://cloud.githubusercontent.com/assets/1017/15855854/92923fb6-2ce4-11e6-9e7a-2f0ef60001c9.png">

I have node.js installed via homebrew, is there anything I'm missing?

**Comment by jjgod** [comment]
`npm install` seems to solve the outDir problem. But I still appreciate help to debug why this is not working for me.

**Comment by jjgod** [comment]
Looks like I'm constantly hitting `write EPIPE`:

![screen shot 2016-06-07 at 7 36 53 pm](https://cloud.githubusercontent.com/assets/1017/15856316/47832294-2ce7-11e6-9332-a8f71dcc3ec1.png)

**Comment by db4** [comment]
Have you succeeded in debugging this? Looks like I have the same issue: the extension silently doesn't work. And the project looks like abandoned: no new commits in last 3 months, no reaction from the author to bug reports...

**Comment by jjgod** [comment]
@db4 I don't have much success still, haven't tried much since.

**Comment by tilman22** [comment]
I'm always using the following setting:
`  "C_Cpp.autocomplete": "Disabled",
`

If completion does not work, you can try out manually:
* Save your file,
* write down the cursor position where you want to do the completion,
* cd into the directory containing the file,
* type (41:9 is the cursor position)
`cat <your_file.cpp> | clang -x c++ -std=c++11 -fsyntax-only -fparse-all-comments -Xclang -code-completion-macros -Xclang -code-completion-brief-comments -Xclang -code-completion-at=-:41:9 -
`
If this succeeds, you get a list of lines starting with "COMPLETION:" (which the extension parses). If this fails, then you get a description of the problem. 
Very likely, you are missing some include files. In this case, add the -I lines (to the above line and to "clang.cxxflags"). Or play around with other compiler options.

Remark: The extension uses `-Xclang -code-completion-at=<stdin>:41:9` instead of `-Xclang -code-completion-at=-:41:9`. `<stdin>` does not work for me on the command line. I'm using my own version of the extension, so I'm not sure if `<stdin>` is working, too.

**Comment by jjgod** [comment]
Thanks, that suggestion works well for me.
